CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
  RETURN (
      WITH CTE AS (
    SELECT *, DENSE_RANK()
    OVER (ORDER BY SALARY DESC)
    AS RNK FROM EMPLOYEE)
SELECT DISTINCT IFNULL(SALARY, NULL) FROM CTE
WHERE RNK=N
);

END